In [1]:
print("hello world")

hello world


In [2]:
import numpy as np
import math

# Normal Python list
my_list = [1, 2, 3, 4, 5]

# Numpy array
my_array = np.array([1, 2, 3, 4, 5])

# Differences:

# 1. Data type:
print("List type:", type(my_list))
print("Array type:", type(my_array))

# 2. Element-wise operations:
list_result = [x * 2 for x in my_list]  # List requires explicit iteration
array_result = my_array * 2             # Numpy array supports vectorized operations

print("List multiplied by 2:", list_result)
print("Array multiplied by 2:", array_result)

# 3. Memory efficiency:
print("List memory size:", my_list.__sizeof__())
print("Array memory size:", my_array.nbytes)

# 4. Slicing and advanced indexing:
print("List slice:", my_list[1:4])
print("Array slice:", my_array[1:4])

# 5. Mathematical functions:
# Lists require manual implementation or use of map
list_sqrt = [math.sqrt(x) for x in my_list]
array_sqrt = np.sqrt(my_array)

print("List sqrt:", list_sqrt)
print("Array sqrt:", array_sqrt)

List type: <class 'list'>
Array type: <class 'numpy.ndarray'>
List multiplied by 2: [2, 4, 6, 8, 10]
Array multiplied by 2: [ 2  4  6  8 10]
List memory size: 88
Array memory size: 40
List slice: [2, 3, 4]
Array slice: [2 3 4]
List sqrt: [1.0, 1.4142135623730951, 1.7320508075688772, 2.0, 2.23606797749979]
Array sqrt: [1.         1.41421356 1.73205081 2.         2.23606798]


create numpy array


In [5]:
arr=np.array([1,2,3,4,5])
print("Array created:", arr)
arr.ndim
arr2=np.array([[1,2,3],[4,5,6]])
print("2D Array created:", arr2)
arr2.ndim


Array created: [1 2 3 4 5]
2D Array created: [[1 2 3]
 [4 5 6]]


2

range function


In [7]:
array=np.arange(1,10,2)
print("Range created:", array)

Range created: [1 3 5 7 9]


linespace function


In [8]:
#linespace function 
#This function is used to create an array of evenly spaced values over a specified range.
arr=np.linspace(0,2,5) #start, stop, numbers blw them
print("Linspace created:", arr)

Linspace created: [0.  0.5 1.  1.5 2. ]


logspace function


In [12]:
#logspace function
#This function is used to create an array of evenly spaced values on a logarithmic scale.
arr=np.logspace(1, 3, 3) #start, stop, numbers blw them  10^1 to 10^3 
print("Logspace created:", arr)

Logspace created: [  10.  100. 1000.]


zeros function

In [16]:
#zeros function
#This function is used to create an array filled with zeros.
arr=np.zeros(5) # Creates a 1D array of zeros with length 5
print("Zeros array created:", arr)
arr2=np.zeros((2,3)) # Creates a 2D array of zeros with shape (2, 3)
print("2D Zeros array created:", arr2)

Zeros array created: [0. 0. 0. 0. 0.]
2D Zeros array created: [[0. 0. 0.]
 [0. 0. 0.]]


ones function

In [17]:
#ones function
#This function is used to create an array filled with ones.
arr=np.ones(5) # Creates a 1D array of zeros with length 5
print("ones array created:", arr)
arr2=np.ones((2,3)) # Creates a 2D array of zeros with shape (2, 3)
print("2D ones array created:", arr2)

ones array created: [1. 1. 1. 1. 1.]
2D ones array created: [[1. 1. 1.]
 [1. 1. 1.]]


full function


In [19]:
#full function
#This function is used to create an array filled with a specified value.
arr=np.full(10,4) # Creates a 1D array of length 10 filled with the value 4
print("Full array created:", arr)
arr2=np.full((2,3),7) # Creates a 2D array of shape (2, 3) filled with the value 7
print("2D Full array created:", arr2)

Full array created: [4 4 4 4 4 4 4 4 4 4]
2D Full array created: [[7 7 7]
 [7 7 7]]


empty function


In [20]:
#empty function
#This function is used to create an array without initializing its values.
arr=np.empty(5) # Creates a 1D array of length 5 without initializing values
print("Empty array created:", arr)
arr2=np.empty((2,3)) # Creates a 2D array of shape (2, 3) without initializing values
print("2D Empty array created:", arr2)

Empty array created: [1. 1. 1. 1. 1.]
2D Empty array created: [[1. 1. 1.]
 [1. 1. 1.]]


random function

In [26]:
#random function
#This function is used to create an array filled with random values.
arr=np.random.rand(10) # Creates a 1D array of random values and they will be uniformly distributed between 0 and 1
print("Random array created:", arr)

arr2=np.random.rand(2,3) # Creates a 2D array of random values with shape (2, 3)
print("2D Random array created:", arr2)

#random.randn function
#This function is used to create an array filled with random values from a standard normal distribution (mean=0, std=1).
arr=np.random.randn(10) # Creates a 1D array of random values from a standard normal distribution
print("Random normal array created:", arr)
arr2=np.random.randn(2,3) # Creates a 2D array of random values from a standard normal distribution with shape (2, 3)
print("2D Random normal array created:", arr2)
#random.randint function
#This function is used to create an array filled with random integers within a specified range.

arr=np.random.randint(1, 10, size=5) # Creates a 1D array of random integers between 1 and 10
print("Random integers array created:", arr)
arr2=np.random.randint(1, 10, size=(2, 3)) # Creates a 2D array of random integers with shape (2, 3)
print("2D Random integers array created:", arr2)





Random array created: [0.98574344 0.99463138 0.67830605 0.20222588 0.30419103 0.07666958
 0.09904393 0.68129834 0.47473459 0.88947329]
2D Random array created: [[0.52443044 0.8716262  0.44248363]
 [0.45700343 0.15366211 0.74311411]]
Random normal array created: [ 0.21648111  0.45760869  0.64141856  0.57680774  1.09182481  0.03311688
 -0.11315444 -0.56223344  0.21149282  0.71552259]
2D Random normal array created: [[ 0.5662932   0.90215622 -0.57558281]
 [-1.29658963  0.48250972 -0.58499456]]
Random integers array created: [4 4 9 5 5]
2D Random integers array created: [[2 8 6]
 [8 1 4]]


numpy datatypes and typecasting


In [ ]:
#datatypes and typecasting
#Numpy supports various data types, including integers, floats, and complex numbers.
arr_int = np.array([1, 2, 3], dtype=np.int32)  # Integer array
arr_float = np.array([1.0, 2.0, 3.0], dtype=np.float64)  # Float array
arr_complex = np.array([1+2j, 3+4j], dtype=np.complex128)  # Complex number array
print("Integer array:", arr_int)
print("Float array:", arr_float)
print("Complex number array:", arr_complex)

#if u change any single element in the array, it will change the whole array to that type
lst= [1, 2, 3.5]  # Mixed list
arr=np.array(lst)
print(arr)
print(arr.dtype)
lst= [1, 2, 3]  # All integers
arr=np.array(lst)
print(arr)
print(arr.dtype)
lst= [1, 2, 3 ,"aa"]  # Mixed list with string
arr=np.array(lst)
print(arr)
print(arr.dtype)


# Typecasting
# You can change the data type of an existing array using the astype() method.
arr=np.array([1,2,3])
print("Original array:", arr)
print("Original array dtype:", arr.dtype)
new_arr = arr.astype(np.float64)  # Convert to float

print("New array:", new_arr)
print("New array dtype:", new_arr.dtype)


#typecasting errros
arr=np.array([1,2,"hello"])
new_arr = arr.astype(np.float64)  # This will raise an error because "hello" cannot be converted to float
# print("New array:", new_arr)  # Uncommenting this line will raise an error  
# # To avoid this, ensure that all elements can be converted to the desired type before using astype().
  



Integer array: [1 2 3]
Float array: [1. 2. 3.]
Complex number array: [1.+2.j 3.+4.j]
[1.  2.  3.5]
float64
[1 2 3]
int64
['1' '2' '3' 'aa']
<U21
Original array: [1 2 3]
Original array dtype: int64
New array: [1. 2. 3.]
New array dtype: float64


creating multidimensional array manually

In [42]:
arr=np.array([[1,2,3]
            ,[4,5,6]])
print("2D Array created manually:", arr)
arr.ndim
arr.shape
arr.size
arr.itemsize #each element size in bytes
# arr.dtype #data type of the array elements

2D Array created manually: [[1 2 3]
 [4 5 6]]


8

reshape function


In [44]:
#reshape function
#This function is used to change the shape of an existing array without changing its data.
arr=np.array([[1,2,3]
            ,[4,5,6]])
print("Original array shape:", arr.shape)
reshaped_arr = arr.reshape(3, 2)  # Reshape to 3
print("Reshaped array:", reshaped_arr)
print("Reshaped array shape:", reshaped_arr.shape)

arr=np.array([1,2,3,4,5,6,7,8,9])
reshapedarr=arr.reshape(3,3) # Reshape to 3x3
print("Reshaped 3x3 array:", reshapedarr)


Original array shape: (2, 3)
Reshaped array: [[1 2]
 [3 4]
 [5 6]]
Reshaped array shape: (3, 2)
Reshaped 3x3 array: [[1 2 3]
 [4 5 6]
 [7 8 9]]
