In [49]:
print("hello world")

hello world


In [50]:
import numpy as np
import math

# Normal Python list
my_list = [1, 2, 3, 4, 5]

# Numpy array
my_array = np.array([1, 2, 3, 4, 5])

# Differences:

# 1. Data type:
print("List type:", type(my_list))
print("Array type:", type(my_array))

# 2. Element-wise operations:
list_result = [x * 2 for x in my_list]  # List requires explicit iteration
array_result = my_array * 2             # Numpy array supports vectorized operations

print("List multiplied by 2:", list_result)
print("Array multiplied by 2:", array_result)

# 3. Memory efficiency:
print("List memory size:", my_list.__sizeof__())
print("Array memory size:", my_array.nbytes)

# 4. Slicing and advanced indexing:
print("List slice:", my_list[1:4])
print("Array slice:", my_array[1:4])

# 5. Mathematical functions:
# Lists require manual implementation or use of map
list_sqrt = [math.sqrt(x) for x in my_list]
array_sqrt = np.sqrt(my_array)

print("List sqrt:", list_sqrt)
print("Array sqrt:", array_sqrt)

List type: <class 'list'>
Array type: <class 'numpy.ndarray'>
List multiplied by 2: [2, 4, 6, 8, 10]
Array multiplied by 2: [ 2  4  6  8 10]
List memory size: 88
Array memory size: 40
List slice: [2, 3, 4]
Array slice: [2 3 4]
List sqrt: [1.0, 1.4142135623730951, 1.7320508075688772, 2.0, 2.23606797749979]
Array sqrt: [1.         1.41421356 1.73205081 2.         2.23606798]


create numpy array


In [51]:
arr=np.array([1,2,3,4,5])
print("Array created:", arr)
arr.ndim
arr2=np.array([[1,2,3],[4,5,6]])
print("2D Array created:", arr2)
arr2.ndim


Array created: [1 2 3 4 5]
2D Array created: [[1 2 3]
 [4 5 6]]


2

range function


In [52]:
array=np.arange(1,10,2)
print("Range created:", array)

Range created: [1 3 5 7 9]


linespace function


In [53]:
#linespace function 
#This function is used to create an array of evenly spaced values over a specified range.
arr=np.linspace(0,2,5) #start, stop, numbers blw them
print("Linspace created:", arr)

Linspace created: [0.  0.5 1.  1.5 2. ]


logspace function


In [54]:
#logspace function
#This function is used to create an array of evenly spaced values on a logarithmic scale.
arr=np.logspace(1, 3, 3) #start, stop, numbers blw them  10^1 to 10^3 
print("Logspace created:", arr)

Logspace created: [  10.  100. 1000.]


zeros function

In [55]:
#zeros function
#This function is used to create an array filled with zeros.
arr=np.zeros(5) # Creates a 1D array of zeros with length 5
print("Zeros array created:", arr)
arr2=np.zeros((2,3)) # Creates a 2D array of zeros with shape (2, 3)
print("2D Zeros array created:", arr2)

Zeros array created: [0. 0. 0. 0. 0.]
2D Zeros array created: [[0. 0. 0.]
 [0. 0. 0.]]


ones function

In [56]:
#ones function
#This function is used to create an array filled with ones.
arr=np.ones(5) # Creates a 1D array of zeros with length 5
print("ones array created:", arr)
arr2=np.ones((2,3)) # Creates a 2D array of zeros with shape (2, 3)
print("2D ones array created:", arr2)

ones array created: [1. 1. 1. 1. 1.]
2D ones array created: [[1. 1. 1.]
 [1. 1. 1.]]


full function


In [57]:
#full function
#This function is used to create an array filled with a specified value.
arr=np.full(10,4) # Creates a 1D array of length 10 filled with the value 4
print("Full array created:", arr)
arr2=np.full((2,3),7) # Creates a 2D array of shape (2, 3) filled with the value 7
print("2D Full array created:", arr2)

Full array created: [4 4 4 4 4 4 4 4 4 4]
2D Full array created: [[7 7 7]
 [7 7 7]]


empty function


In [58]:
#empty function
#This function is used to create an array without initializing its values.
arr=np.empty(5) # Creates a 1D array of length 5 without initializing values
print("Empty array created:", arr)
arr2=np.empty((2,3)) # Creates a 2D array of shape (2, 3) without initializing values
print("2D Empty array created:", arr2)

Empty array created: [1. 1. 1. 1. 1.]
2D Empty array created: [[1. 1. 1.]
 [1. 1. 1.]]


random function

In [59]:
#random function
#This function is used to create an array filled with random values.
arr=np.random.rand(10) # Creates a 1D array of random values and they will be uniformly distributed between 0 and 1
print("Random array created:", arr)

arr2=np.random.rand(2,3) # Creates a 2D array of random values with shape (2, 3)
print("2D Random array created:", arr2)

#random.randn function
#This function is used to create an array filled with random values from a standard normal distribution (mean=0, std=1).
arr=np.random.randn(10) # Creates a 1D array of random values from a standard normal distribution
print("Random normal array created:", arr)
arr2=np.random.randn(2,3) # Creates a 2D array of random values from a standard normal distribution with shape (2, 3)
print("2D Random normal array created:", arr2)
#random.randint function
#This function is used to create an array filled with random integers within a specified range.

arr=np.random.randint(1, 10, size=5) # Creates a 1D array of random integers between 1 and 10
print("Random integers array created:", arr)
arr2=np.random.randint(1, 10, size=(2, 3)) # Creates a 2D array of random integers with shape (2, 3)
print("2D Random integers array created:", arr2)





Random array created: [0.7219094  0.70363214 0.48900214 0.21470852 0.29944116 0.37865587
 0.48861865 0.75534378 0.76216984 0.56358068]
2D Random array created: [[0.63395391 0.85384397 0.09528433]
 [0.4327284  0.92152453 0.52377057]]
Random normal array created: [ 0.23837273  1.01713055  0.09223802 -1.29556225  0.10137995  0.73824005
 -1.12358364  0.48392703 -0.76902092 -1.08484498]
2D Random normal array created: [[-0.25540542  1.40535553 -1.39779372]
 [ 1.18436533 -0.89378419  0.78456237]]
Random integers array created: [9 1 1 1 7]
2D Random integers array created: [[3 1 1]
 [3 7 1]]


numpy datatypes and typecasting


In [60]:
#datatypes and typecasting
#Numpy supports various data types, including integers, floats, and complex numbers.
arr_int = np.array([1, 2, 3], dtype=np.int32)  # Integer array
arr_float = np.array([1.0, 2.0, 3.0], dtype=np.float64)  # Float array
arr_complex = np.array([1+2j, 3+4j], dtype=np.complex128)  # Complex number array
print("Integer array:", arr_int)
print("Float array:", arr_float)
print("Complex number array:", arr_complex)

#if u change any single element in the array, it will change the whole array to that type
lst= [1, 2, 3.5]  # Mixed list
arr=np.array(lst)
print(arr)
print(arr.dtype)
lst= [1, 2, 3]  # All integers
arr=np.array(lst)
print(arr)
print(arr.dtype)
lst= [1, 2, 3 ,"aa"]  # Mixed list with string
arr=np.array(lst)
print(arr)
print(arr.dtype)


# Typecasting
# You can change the data type of an existing array using the astype() method.
arr=np.array([1,2,3])
print("Original array:", arr)
print("Original array dtype:", arr.dtype)
new_arr = arr.astype(np.float64)  # Convert to float

print("New array:", new_arr)
print("New array dtype:", new_arr.dtype)


#typecasting errros
arr=np.array([1,2,"hello"])
#ew_arr = arr.astype(np.float64)  # This will raise an error because "hello" cannot be converted to float
# print("New array:", new_arr)  # Uncommenting this line will raise an error  
# # To avoid this, ensure that all elements can be converted to the desired type before using astype().
  



Integer array: [1 2 3]
Float array: [1. 2. 3.]
Complex number array: [1.+2.j 3.+4.j]
[1.  2.  3.5]
float64
[1 2 3]
int64
['1' '2' '3' 'aa']
<U21
Original array: [1 2 3]
Original array dtype: int64
New array: [1. 2. 3.]
New array dtype: float64


creating multidimensional array manually

In [61]:
arr=np.array([[1,2,3]
            ,[4,5,6]])
print("2D Array created manually:", arr)
arr.ndim
arr.shape
arr.size
arr.itemsize #each element size in bytes
# arr.dtype #data type of the array elements

2D Array created manually: [[1 2 3]
 [4 5 6]]


8

reshape function


In [62]:
#reshape function
#This function is used to change the shape of an existing array without changing its data.
arr=np.array([[1,2,3]
            ,[4,5,6]])
print("Original array shape:", arr.shape)
reshaped_arr = arr.reshape(3, 2)  # Reshape to 3
print("Reshaped array:", reshaped_arr)
print("Reshaped array shape:", reshaped_arr.shape)

arr=np.array([1,2,3,4,5,6,7,8,9])
reshapedarr=arr.reshape(3,3) # Reshape to 3x3
print("Reshaped 3x3 array:", reshapedarr)


Original array shape: (2, 3)
Reshaped array: [[1 2]
 [3 4]
 [5 6]]
Reshaped array shape: (3, 2)
Reshaped 3x3 array: [[1 2 3]
 [4 5 6]
 [7 8 9]]


ravel function

In [63]:
#ravel function
#This function is used to flatten a multi-dimensional array into a 1D array .

print(reshapedarr)
raveled_arr = reshapedarr.ravel()  # Flatten the array
print("Raveled array:", raveled_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Raveled array: [1 2 3 4 5 6 7 8 9]


flatten function


In [64]:
#flatten function
#This function is used to flatten a multi-dimensional array into a 1D array.
# It returns a copy of the original array.
flattened_arr = reshapedarr.flatten() 
flattened_arr[2]=200 # Flatten the array
print("Flattened array:", flattened_arr)
print("Original array remains unchanged:", reshapedarr)

Flattened array: [  1   2 200   4   5   6   7   8   9]
Original array remains unchanged: [[1 2 3]
 [4 5 6]
 [7 8 9]]


arithmatic operations 

In [65]:
#arithmatic operations
# Numpy supports element-wise arithmetic operations on arrays.
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
sum_arr = arr1 + arr2  # Element-wise addition
diff_arr = arr1 - arr2  # Element-wise subtraction
print("Sum of arrays:", sum_arr)
print("Difference of arrays:", diff_arr)

# Element-wise multiplication and division
mul_arr = arr1 * arr2  # Element-wise multiplication
div_arr = arr1 / arr2  # Element-wise division
print("Product of arrays:", mul_arr)
print("Division of arrays:", div_arr)
# Element-wise exponentiation
exp_arr = arr1 ** 2  # Element-wise exponentiation
print("Exponentiation of array:", exp_arr)
# Element-wise square root
sqrt_arr = np.sqrt(arr1)  # Element-wise square root
print("Square root of array:", sqrt_arr)
# Element-wise logarithm
log_arr = np.log(arr1)  # Element-wise natural logarithm
print("Natural logarithm of array:", log_arr)
# Element-wise sine and cosine
sin_arr = np.sin([0,np.pi/2,np.pi])  # Element-wise sine
cos_arr = np.cos([0,np.pi/2,np.pi])  # Element-wise cosine
print("Sine of array:", sin_arr)
print("Cosine of array:", cos_arr)



Sum of arrays: [5 7 9]
Difference of arrays: [-3 -3 -3]
Product of arrays: [ 4 10 18]
Division of arrays: [0.25 0.4  0.5 ]
Exponentiation of array: [1 4 9]
Square root of array: [1.         1.41421356 1.73205081]
Natural logarithm of array: [0.         0.69314718 1.09861229]
Sine of array: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Cosine of array: [ 1.000000e+00  6.123234e-17 -1.000000e+00]


indexing and slicing

In [66]:
#indexing and slicing
# Numpy supports advanced indexing and slicing techniques.
arr=np.array([1,2,3,4,5,6])
print(arr[3])
print(arr[-1])  # Negative indexing (last element)
print(arr[-2])  # Second last element
print(arr[1:4])  # Slicing from index 1 to 3 (exclusive )
print(arr[:3])   # Slicing from the start to index 2 (exclusive)
print(arr[3:])   # Slicing from index 3 to the end
print(arr[::2])  # Slicing with a step of 2 (every second element)
print(arr[::-1])  # Reversing the array using slicing
print(arr[1:5:2])  # Slicing with a step of 2 (from index 1 to 4)
print(arr[1:5:2])  # Slicing with a step of 2 (from index 1 to 4)
print(arr[: : 2]) # Slicing with a step of 2 (from start to end)

print("\n")
print("\n")
#multidimensional indexing and slicing
# Numpy supports advanced indexing and slicing techniques for multi-dimensional arrays.
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D Array:")
print(arr2d)
print("Element at (1, 2):", arr2d[1, 2])  # Accessing element at row 1, column 2
print("Row 1:", arr2d[1])  # Accessing entire row
print("Column 2:", arr2d[:, 2])  # Accessing entire column
print("Sub-array (0:2, 1:3):")
print(arr2d[0:2, 1:3])  # Slicing a sub-array (rows 0 to 1, columns 1 to 2)
print("Reversed 2D Array:")
print(arr2d[::-1, ::-1])  # Reversing the entire 2D array



4
6
5
[2 3 4]
[1 2 3]
[4 5 6]
[1 3 5]
[6 5 4 3 2 1]
[2 4]
[2 4]
[1 3 5]




2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at (1, 2): 6
Row 1: [4 5 6]
Column 2: [3 6 9]
Sub-array (0:2, 1:3):
[[2 3]
 [5 6]]
Reversed 2D Array:
[[9 8 7]
 [6 5 4]
 [3 2 1]]


looping in arrays'

In [67]:
arr=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D Array:")
print(arr)
#looping in arrays
for x in np.nditer(arr):
    print(x, end=' ')  # Iterating through each element in the array
print("\n")
for ind,x in np.ndenumerate(arr):
    print(ind,x, )  # Iterating through each element with its index



2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
1 2 3 4 5 6 7 8 9 

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(2, 0) 7
(2, 1) 8
(2, 2) 9


views vs copy

In [68]:
#views vs copy
# Numpy arrays can be viewed as either views or copies of the original data.
arr = np.array([1, 2, 3, 4, 5])
view_arr = arr.view()  # Create a view of the original array
print("Original array:", arr)
view_arr[0] = 10  # Modify the view
print("View of the array:", view_arr)
print("Original array but changed :", arr)
print("\n")
#copy
# Create a copy of the original array
copy_arr = arr.copy()  # Create a copy of the original array
copy_arr[0] = 20  # Modify the copy
print("Copy of the array:", copy_arr)
print("Original array remains unchanged:", arr)  # Original array remains unchanged
# A view shares the same data as the original array, while a copy creates a new array


Original array: [1 2 3 4 5]
View of the array: [10  2  3  4  5]
Original array but changed : [10  2  3  4  5]


Copy of the array: [20  2  3  4  5]
Original array remains unchanged: [10  2  3  4  5]


transpose of the matrix

In [69]:
#transpose of the matrix
# Numpy supports matrix transposition using the T attribute or the transpose() method.
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original array:")
print(arr)
print("\n")
transposed_arr = arr.T  # Transpose the array using T attribute
print("Transposed array using T attribute:")
print(transposed_arr)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Transposed array using T attribute:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


swapaxes in numpy

In [70]:
#swapaxes in numpy
# The swapaxes() function is used to swap two axes of an array.
arr = np.array([[[1, 2, 3], [4, 5, 6]]])
print("Original array:")
print(arr)
print(arr.shape)
print("\n")
swapped_arr = arr.swapaxes(0, 1)  # Swap axes 0 and 1
print("Array after swapping axes 0 and 1:")
print(swapped_arr)
print(swapped_arr.shape)

Original array:
[[[1 2 3]
  [4 5 6]]]
(1, 2, 3)


Array after swapping axes 0 and 1:
[[[1 2 3]]

 [[4 5 6]]]
(2, 1, 3)


concatenation

In [71]:
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
#concatenation
# Numpy supports concatenation of arrays along specified axes.
concatenated_arr = np.concatenate((arr1, arr2))  # Concatenate along the first axis (default)
#vstacking
vstacked_arr = np.vstack((arr1, arr2))  # Stack arrays vertically (along rows)
#hstacking
hstacked_arr = np.hstack((arr1, arr2))  # Stack arrays horizontally (along columns)
print("Concatenated array:", concatenated_arr)
print("Vertically stacked array:")
print(vstacked_arr)
print("Horizontally stacked array:")
print(hstacked_arr)


Concatenated array: [1 2 3 4 5 6 7 8]
Vertically stacked array:
[[1 2 3 4]
 [5 6 7 8]]
Horizontally stacked array:
[1 2 3 4 5 6 7 8]


spliting in arrays

In [72]:
#splitting in ararys
# Numpy supports splitting arrays into multiple sub-arrays along specified axes.
split_arr = np.split(arr1, 2)  # Split the array into 2 sub-arrays in uniform way
print("Original array:", arr1)
print("Split array into 2 sub-arrays:")
print(split_arr)


Original array: [1 2 3 4]
Split array into 2 sub-arrays:
[array([1, 2]), array([3, 4])]


repeat vs tile 

In [73]:
#repeat vs tile
# The repeat() function is used to repeat elements of an array, while the tile() function is used to repeat the entire array.

arr= np.array([1, 2, 3])
print("Original array:", arr)
repeat_arr = np.repeat(arr, 2)  # Repeat each element twice
tile_arr = np.tile(arr, 2)  # Repeat the entire array twice
print("Array after repeating each element twice:", repeat_arr)
print("Array after tiling the entire array twice:", tile_arr)


Original array: [1 2 3]
Array after repeating each element twice: [1 1 2 2 3 3]
Array after tiling the entire array twice: [1 2 3 1 2 3]


aggregate functions

In [74]:
#aggregate functions
# Numpy provides various aggregate functions to perform operations on arrays.
arr = np.array([1, 2, 3, 4, 5])
print("Original array:", arr)
print("Sum of array elements:", np.sum(arr))  # Sum of elements
print("Mean of array elements:", np.mean(arr))  # Mean of elements
print("Standard deviation of array elements:", np.std(arr))  # Standard deviation
print("Variance of array elements:", np.var(arr))  # Variance of elements

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original matrix:")
print(matrix)
print("Sum of each column:", np.sum(matrix, axis=0))  # Sum along columns
print("Sum of each row:", np.sum(matrix, axis=1))  # Sum along
# rows
print("Maximum element in the matrix:", np.max(matrix))  # Maximum element
print("Minimum element in the matrix:", np.min(matrix))  # Minimum element

#cumulative functions
# Numpy provides cumulative functions to perform operations on arrays.
cumulative_sum = np.cumsum(arr)  # Cumulative sum
cumulative_product = np.cumprod(arr)  # Cumulative product
print("Cumulative sum of array elements:", cumulative_sum)
print("Cumulative product of array elements:", cumulative_product)

#sort function
# Numpy provides a sort function to sort arrays.
sorted_arr = np.sort(arr)  # Sort the array in ascending order
print("Sorted array:", sorted_arr)
# Sorting a 2D array along a specified axis
sorted_matrix = np.sort(matrix, axis=0)  # Sort each column in ascending order
print("Sorted matrix along columns:")
print(sorted_matrix)




Original array: [1 2 3 4 5]
Sum of array elements: 15
Mean of array elements: 3.0
Standard deviation of array elements: 1.4142135623730951
Variance of array elements: 2.0
Original matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum of each column: [12 15 18]
Sum of each row: [ 6 15 24]
Maximum element in the matrix: 9
Minimum element in the matrix: 1
Cumulative sum of array elements: [ 1  3  6 10 15]
Cumulative product of array elements: [  1   2   6  24 120]
Sorted array: [1 2 3 4 5]
Sorted matrix along columns:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


conditional based choices

In [75]:
#where function
# The where() function is used to find indices of elements that satisfy a specified condition.
arr = np.array([1, 2, 3, 4, 5])
condition = arr > 3  # Condition to find elements greater than 3
indices = np.where(condition)  # Find indices of elements satisfying the condition
print("Indices of elements greater than 3:", indices)
print("Elements greater than 3:", arr[indices])  # Access elements using the indices
result =np.where(arr>3, "Greater than 3", "Less than or equal to 3")  # Conditional choice
print("Conditional choice result:", result)  # Result based on the condition

Indices of elements greater than 3: (array([3, 4]),)
Elements greater than 3: [4 5]
Conditional choice result: ['Less than or equal to 3' 'Less than or equal to 3'
 'Less than or equal to 3' 'Greater than 3' 'Greater than 3']


argwhere for 2d arrays


In [76]:
#argwhere for 2d arrays
# The argwhere() function is used to find indices of elements that satisfy a specified condition in
# multi-dimensional arrays.
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
condition_2d = arr2d > 5  # Condition to find elements greater than 5
indices_2d = np.argwhere(condition_2d)  # Find indices of elements satisfying the condition
print("Indices of elements greater than 5 in 2D array:", indices_2d)
print("Elements greater than 5 in 2D array:", arr2d[indices_2d])  # Access elements using the indices

Indices of elements greater than 5 in 2D array: [[1 2]
 [2 0]
 [2 1]
 [2 2]]
Elements greater than 5 in 2D array: [[[4 5 6]
  [7 8 9]]

 [[7 8 9]
  [1 2 3]]

 [[7 8 9]
  [4 5 6]]

 [[7 8 9]
  [7 8 9]]]


advanced conditional functions

In [77]:
import numpy as np
mask=np.logical_and(arr2d > 5, arr2d < 9)  # Create a mask for elements greater than 5 and less than 9
print(arr2d)
print("Mask for elements greater than 5 and less than 9:")  
print(mask)  # Display the mask

mask1=np.logical_or(arr2d > 1, arr2d < 4)  # Create a mask for elements greater than 5 or less than 9
print("Mask for elements greater than 5 or less than 9:")   
print(mask1)  # Display the mask

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Mask for elements greater than 5 and less than 9:
[[False False False]
 [False False  True]
 [ True  True False]]
Mask for elements greater than 5 or less than 9:
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


nonzero function

In [78]:
list=[1,2,0,0,3,4,0,0,5]
arr=np.nonzero(list)  # Find indices of non-zero elements
print("Indices of non-zero elements:",arr)  # Display the indices of non-zero elements

Indices of non-zero elements: (array([0, 1, 4, 5, 8]),)


broadcasting

In [79]:
#broadcasting
# Numpy supports broadcasting, which allows operations on arrays of different shapes.
#strech the shape of the smaller array to match the shape of the larger array
arr1 = np.array([1, 2, 3]) #  # 1D array with shape (3,1)
arr2 = np.array([[4], [5], [6]])  # 2D array with shape (3, 1)
print("Array 1:", arr1)
print("Array 2:")
print(arr2)
print("Array 1 + Array 2:")
print(arr1 + arr2)  # Broadcasting allows addition of arrays with different shapes (3,1) and (3,1 ) is (3,3)
# either of the arrays can be 1D or 2D, as long as they are compatible for broadcasting. broadcasating of arrays of shape 2,3 and 3,2 is ont possible because either of them are not a 1d array


Array 1: [1 2 3]
Array 2:
[[4]
 [5]
 [6]]
Array 1 + Array 2:
[[5 6 7]
 [6 7 8]
 [7 8 9]]


applicatioon of broadcasting

In [80]:
image=np.array([[200,150],[100,250]])
# Application of broadcasting in image processing
# Adding a constant value to the image array
brightness=image + 50  # Increase brightness by 50
print("Original image array:")
print(image)
print("Brightness adjusted image array:")
print(brightness)  # Display the adjusted image array

Original image array:
[[200 150]
 [100 250]]
Brightness adjusted image array:
[[250 200]
 [150 300]]


vectorization

In [81]:
#vectorization
# Numpy supports vectorization, which allows operations on entire arrays without explicit loops.    
arr = np.array([1, 2, 3, 4, 5])
# Vectorized operation: squaring each element
squared_arr = arr ** 2  # Square each element
print("Original array:", arr)
print("Squared array:", squared_arr)  # Display the squared array

def square(x):
    return x *x
vfunc=np.vectorize(square)  # Vectorize the square function
arr = np.array([1, 2, 3, 4, 5])
squared_arr = vfunc(arr)  # Apply the vectorized function to the array
print("Original array:", arr)
print("Squared array using vectorization:", squared_arr)  # Display the squared array using vectorization


#disadvantages of vectorization
# While vectorization is powerful, it can lead to memory issues for very large arrays.
# For example, if you try to create a very large array, it may exceed available memory.
# Example of a large array that may cause memory issues
try:
    large_array = np.ones((100000, 100000))  # Attempt to create a very large array
except MemoryError as e:
    print("MemoryError:", e)
# The above code may raise a MemoryError if the system does not have enough memory to allocate for the large array.



Original array: [1 2 3 4 5]
Squared array: [ 1  4  9 16 25]
Original array: [1 2 3 4 5]
Squared array using vectorization: [ 1  4  9 16 25]
MemoryError: Unable to allocate 74.5 GiB for an array with shape (100000, 100000) and data type float64


dealing with missiing values

In [83]:
#dealling with missing values
# Numpy provides functions to handle missing values in arrays.
arr = np.array([1, 2, np.nan, 4, 5])  # Array with a missing value (NaN)
print("Original array with missing value:", arr)

#np.inf and -np.inf represent positive and negative infinity, respectively.
arr_with_inf = np.array([1, 2, np.inf, -np.inf, 5])  # Array with positive and negative infinity
print("Array with positive and negative infinity:", arr_with_inf)
print("Is NaN in array:", np.isnan(arr))  # Check for NaN values
print("Is Inf in array:", np.isinf(arr_with_inf))  # Check for Inf
print("Is finite in array:", np.isfinite(arr_with_inf))  # Check for finite values
# Replacing NaN with a specific value (e.g., 0)
arr_filled = np.nan_to_num(arr, nan=0)  # Replace NaN with 0
print("Array after replacing NaN with 0:", arr_filled)
# Replacing Inf with a specific value (e.g., 0)
arr_with_inf_filled = np.nan_to_num(arr_with_inf, posinf=0, neginf=0)  # Replace Inf with 0
print("Array after replacing Inf with 0:", arr_with_inf_filled)




Original array with missing value: [ 1.  2. nan  4.  5.]
Array with positive and negative infinity: [  1.   2.  inf -inf   5.]
Is NaN in array: [False False  True False False]
Is Inf in array: [False False  True  True False]
Is finite in array: [ True  True False False  True]
Array after replacing NaN with 0: [1. 2. 0. 4. 5.]
Array after replacing Inf with 0: [1. 2. 0. 0. 5.]
