In [2]:
print("hello")
import numpy as np

hello


multiplication of two numpy array usinf dot function

In [6]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Matrix B
b= np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

# Element-wise multiplication
print(a*b)
print("\n")
# Matrix multiplication
print(np.dot(a, b))

[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


numpy programs web string functions 

In [15]:
s=np.array(["I","love","Python","and","Numpy"])
upper=np.char.upper(s)
print(upper)
lower=np.char.lower(s)
print(lower)
capitalizze=np.char.capitalize(s)
print(capitalizze)
title_case=np.char.title(s)
print(title_case)

print(np.char.swapcase(s))




['I' 'LOVE' 'PYTHON' 'AND' 'NUMPY']
['i' 'love' 'python' 'and' 'numpy']
['I' 'Love' 'Python' 'And' 'Numpy']
['I' 'Love' 'Python' 'And' 'Numpy']
['i' 'LOVE' 'pYTHON' 'AND' 'nUMPY']


get tow numbers of numpy array if any elements is having larger value than a specifies value


In [24]:
arr = np.array([[ 1,  2,  3,  4,  5],
                [ 6,  7,  8,  9, 10],
                [11, 12, 13, 14, 15],
                [16, 17, 18, 19, 20],
                [21, 22, 23, 24, 25]])


x=10
# np.any(arr > x,axis=1) 
res=np.where(np.any(arr > x,axis=1))
res[0]
 # Check if any element is greater than 10


array([2, 3, 4])

how to remove rows which contains null values in a numpy array